### ISSUE TITLE
Broken push 

### ISSUE THREAD

**Issue by palladius** [palladius/palladius.github.io#1]
I've noticed that there is a github action which tries to push but fails.

**Comment by palladius** [comment]
Error:

```
Run actions/jekyll-build-pages@v1
  with:
    source: .
    destination: ./_site
    future: false
    build_revision: 03e00b371647949099179c379c187ef35[2](https://github.com/palladius/palladius.github.io/actions/runs/11871840364/job/33084847389#step:4:2)009562
    verbose: true
    token: ***
/usr/bin/docker run --name ghcrioactionsjekyllbuildpagesv101[3](https://github.com/palladius/palladius.github.io/actions/runs/11871840364/job/33084847389#step:4:3)_aa27cc --label 155[4](https://github.com/palladius/palladius.github.io/actions/runs/11871840364/job/33084847389#step:4:4)90 --workdir /github/workspace --rm -e "INPUT_SOURCE" -e "INPUT_DESTINATION" -e "INPUT_FUTURE" -e "INPUT_BUILD_REVISION" -e "INPUT_VERBOSE" -e "INPUT_TOKEN" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_ENVIRONMENT" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e "ACTIONS_ID_TOKEN_REQUEST_URL" -e "ACTIONS_ID_TOKEN_REQUEST_TOKEN" -e "ACTIONS_RESULTS_URL" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/palladius.github.io/palladius.github.io":"/github/workspace" ghcr.io/actions/jekyll-build-pages:v1.0.13
Configuration file: none
To use retry middleware with Faraday v2.0+, install `faraday-retry` gem
       Deprecation: A call to '{% post_url 2022-01-08-welcome-to-jekyll %}' did not match a post using the new matching method of checking name (path-date-slug) equality. Please make sure that you change this tag to match the post's name exactly.
  Liquid Exception: Could not locate the included file 'gallery-layout.html' in any of ["/github/workspace/_includes", "/usr/local/bundle/gems/jekyll-theme-primer-0.6.0/_includes"]. Ensure it exists in one of those directories and is not a symlink as those are not allowed in safe mode. in blog/fotoricc/galleries/20220109-snow-in-uetliberg.md
/usr/local/bundle/gems/jekyll-3.10.0/lib/jekyll/tags/include.rb:121:in `locate_include_file': Could not locate the included file 'gallery-layout.html' in any of ["/github/workspace/_includes", "/usr/local/bundle/gems/jekyll-theme-primer-0.6.0/_includes"]. Ensure it exists in one of those directories and is not a symlink as those are not allowed in safe mode. (IOError)
	from /usr/local/bundle/gems/jekyll-3.10.0/lib/jekyll/tags/include.rb:130:in `render'
	from /usr/local/bundle/gems/liquid-4.0.4/lib/liquid/block_body.rb:103:in `render_node_to_output'
	from /usr/local/bundle/gems/liquid-4.0.4/lib/liquid/block_body.rb:91:in `render'
	from /usr/local/bundle/gems/liquid-4.0.4/lib/liquid/template.rb:206:in `block in render'
	from /usr/local/bundle/gems/liquid-4.0.4/lib/liquid/template.rb:240:in `with_profiling'
	from /usr/local/bundle/gems/liquid-4.0.4/lib/liquid/template.rb:20[5](https://github.com/palladius/palladius.github.io/actions/runs/11871840364/job/33084847389#step:4:5):in `render'
	from /usr/local/bundle/gems/liquid-4.0.4/lib/liquid/template.rb:218:in `render!'
	from /usr/local/bundle/gems/jekyll-3.10.0/lib/jekyll/liquid_renderer/file.rb:30:in `block (2 levels) in render!'
	from /usr/local/bundle/gems/jekyll-3.10.0/lib/jekyll/liquid_renderer/file.rb:42:in `measure_bytes'
	from /usr/local/bundle/gems/jekyll-3.10.0/lib/jekyll/liquid_renderer/file.rb:29:in `block in render!'
	from /usr/local/bundle/gems/jekyll-3.10.0/lib/jekyll/liquid_renderer/file.rb:49:in `measure_time'
	from /usr/local/bundle/gems/jekyll-3.10.0/lib/jekyll/liquid_renderer/file.rb:28:in `render!'
	from /usr/local/bundle/gems/jekyll-3.10.0/lib/jekyll/renderer.rb:12[6](https://github.com/palladius/palladius.github.io/actions/runs/11871840364/job/33084847389#step:4:6):in `render_liquid'
	from /usr/local/bundle/gems/jekyll-3.10.0/lib/jekyll/renderer.rb:[7](https://github.com/palladius/palladius.github.io/actions/runs/11871840364/job/33084847389#step:4:7)9:in `render_document'
	from /usr/local/bundle/gems/jekyll-3.10.0/lib/jekyll/renderer.rb:62:in `run'
	from /usr/local/bundle/gems/jekyll-3.10.0/lib/jekyll/site.rb:479:in `render_regenerated'
	from /usr/local/bundle/gems/jekyll-3.10.0/lib/jekyll/site.rb:472:in `block in render_pages'
	from /usr/local/bundle/gems/jekyll-3.10.0/lib/jekyll/site.rb:471:in `each'
	from /usr/local/bundle/gems/jekyll-3.10.0/lib/jekyll/site.rb:471:in `render_pages'
	from /usr/local/bundle/gems/jekyll-3.10.0/lib/jekyll/site.rb:192:in `render'
	from /usr/local/bundle/gems/jekyll-3.10.0/lib/jekyll/site.rb:71:in `process'
	from /usr/local/bundle/gems/jekyll-3.10.0/lib/jekyll/command.rb:2[8](https://github.com/palladius/palladius.github.io/actions/runs/11871840364/job/33084847389#step:4:8):in `process_site'
	from /usr/local/bundle/gems/jekyll-3.10.0/lib/jekyll/commands/build.rb:65:in `build'
	from /usr/local/bundle/gems/jekyll-3.10.0/lib/jekyll/commands/build.rb:36:in `process'
	from /usr/local/bundle/gems/github-pages-232/bin/github-pages:70:in `block (3 levels) in <top (required)>'
	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary.rb:1[9](https://github.com/palladius/palladius.github.io/actions/runs/11871840364/job/33084847389#step:4:10):in `program'
	from /usr/local/bundle/gems/github-pages-232/bin/github-pages:6:in `<top (required)>'
	from /usr/local/bundle/bin/github-pages:25:in `load'
	from /usr/local/bundle/bin/github-pages:25:in `<main>'
Error:  Logging at level: debug GitHub Pages: github-pages v232 GitHub Pages: jekyll v3.10.0 Theme: jekyll-theme-primer Theme source: /usr/local/bundle/gems/jekyll-theme-primer-0.6.0 Requiring: jekyll-github-metadata Requiring: jekyll-seo-tag Requiring: jekyll-coffeescript Requiring: jekyll-commonmark-ghpages Requiring: jekyll-gist Requiring: jekyll-github-metadata Requiring: jekyll-paginate Requiring: jekyll-relative-links Requiring: jekyll-optional-front-matter Requiring: jekyll-readme-index Requiring: jekyll-default-layout Requiring: jekyll-titles-from-headings GitHub Metadata: Initializing... Source: /github/workspace/. Destination: /github/workspace/./_site Incremental build: disabled. Enable with --incremental Generating... Reading: blog/_posts/2022-01-08-welcome-to-jekyll.markdown Reading: blog/_posts/2022-01-08-welcome-to-sreccardo.md Generating: JekyllOptionalFrontMatter::Generator finished in 0.000273843 seconds. Generating: JekyllReadmeIndex::Generator finished in 0.002277694 seconds. Generating: Jekyll::Paginate::Pagination finished in 4.277e-06 seconds. GitHub Metadata: Generating for palladius/palladius.github.io GitHub Metadata: Calling @client.pages("palladius/palladius.github.io", {}) Generating: JekyllRelativeLinks::Generator finished in 0.130796465 seconds. Generating: JekyllDefaultLayout::Generator finished in 0.00021385 seconds. Requiring: kramdown-parser-gfm Generating: JekyllTitlesFromHeadings::Generator finished in 0.00780327 seconds. Rendering: blog/_posts/2022-01-08-welcome-to-sreccardo.md Pre-Render Hooks: blog/_posts/2022-01-08-welcome-to-sreccardo.md Rendering Liquid: blog/_posts/2022-01-08-welcome-to-sreccardo.md Requiring: rouge Requiring: kramdown-parser-gfm Rendering Markup: blog/_posts/2022-01-08-welcome-to-sreccardo.md Rendering Layout: blog/_posts/2022-01-08-welcome-to-sreccardo.md Layout source: theme GitHub Metadata: Calling @client.organization("palladius") GitHub Metadata: Calling @client.user("palladius") Rendering: blog/_posts/2022-01-08-welcome-to-sreccardo.md/#excerpt Pre-Render Hooks: blog/_posts/2022-01-08-welcome-to-sreccardo.md/#excerpt Rendering Liquid: blog/_posts/2022-01-08-welcome-to-sreccardo.md/#excerpt Rendering Markup: blog/_posts/2022-01-08-welcome-to-sreccardo.md/#excerpt GitHub Metadata: Calling @client.repository("palladius/palladius.github.io", {:accept=>"application/vnd.github.drax-preview+json"}) Rendering: blog/_posts/2022-01-08-welcome-to-jekyll.markdown Pre-Render Hooks: blog/_posts/2022-01-08-welcome-to-jekyll.markdown Rendering Liquid: blog/_posts/2022-01-08-welcome-to-jekyll.markdown Requiring: kramdown-parser-gfm Rendering Markup: blog/_posts/2022-01-08-welcome-to-jekyll.markdown Rendering Layout: blog/_posts/2022-01-08-welcome-to-jekyll.markdown Layout source: theme Rendering: blog/_posts/2022-01-08-welcome-to-jekyll.markdown/#excerpt Pre-Render Hooks: blog/_posts/2022-01-08-welcome-to-jekyll.markdown/#excerpt Rendering Liquid: blog/_posts/2022-01-08-welcome-to-jekyll.markdown/#excerpt Requiring: kramdown-parser-gfm Rendering Markup: blog/_posts/2022-01-08-welcome-to-jekyll.markdown/#excerpt Rendering: blog/fotoricc/galleries/20220[10](https://github.com/palladius/palladius.github.io/actions/runs/11871840364/job/33084847389#step:4:11)9-snow-in-uetliberg.md Pre-Render Hooks: blog/fotoricc/galleries/20220109-snow-in-uetliberg.md Rendering Liquid: blog/fotoricc/galleries/20220109-snow-in-uetliberg.md github-pages 232 | Error: Could not locate the included file 'gallery-layout.html' in any of ["/github/workspace/_includes", "/usr/local/bundle/gems/jekyll-theme-primer-0.6.0/_includes"]. Ensure it exists in one of those directories and is not a symlink as those are not allowed in safe mode.
```

**Comment by palladius** [comment]
unfortunately the last time it worked was 2022 and it seems like github only keeps the last 10.

**Comment by palladius** [comment]
I have a strong feeling github pages is NOT calling my dockerfile.. I need to dig deeper
